version: '2'
services:
  zookeeper01:
    image: zookeeper
    ports:
      - "2181:2181"     
    container_name: myzookeeper01

  zookeeper02:
    image: zookeeper
    ports:
      - "2182:2181"     
    container_name: myzookeeper02
            
  kafka01:
    image: wurstmeister/kafka       
    volumes: 
        - /etc/localtime:/etc/localtime 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 47.106.81.161
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2182
    container_name: kafka01                     

  kafka02:
    image: wurstmeister/kafka       
    volumes: 
        - /etc/localtime:/etc/localtime 
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 47.106.81.161
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2182
    container_name: kafka02             

  kafka-manager:  
    image: sheepkiller/kafka-manager                
    environment:
        ZK_HOSTS: 47.106.81.161                   
    ports:  
      - "9000:9000"                                 
